name: deploy
on:
  workflow_dispatch:

jobs:    
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - uses: Azure/k8s-deploy@v4
        with: 
          namespace: 'myapp'
          images: 'contoso.azurecr.io/myapp:${{ event.run_id }}'
          imagepullsecrets: |
            image-pull-secret1
            image-pull-secret2
          manifests: |
            deployment.yaml
            service.yaml
            dir/manifestsDirectory
          strategy: canary
          action: deploy
          percentage: 20
